feat: refetch monitors on delete
chamanbravo/upstat pull request #27
Opened 2024-02-25 09:44 UTC by jeyren95

[https://github.com/chamanbravo/upstat/issues/24](url)

2024-02-26 16:03 UTC, chamanbravo requested changes

2024-02-27 14:00 UTC, jeyren95 commented on web/src/pages/StatusPages/StatusPagesTable/DataTable.tsx
> -// this declaration is required for typing in action column cell function
This declaration is global to all tables according to the docs [https://tanstack.com/table/latest/docs/api/core/column-def#meta](url)

This declaration is already defined in the "NotificationChannelTable/DataTable" file.
Having repeated declarations would mean that we will have to update the extended interface for each declaration if we want to add anymore properties to this interface

2024-02-27 14:05 UTC, jeyren95 commented on web/src/pages/Notifications/NotificationChannelTable/DataTable.tsx
> +    deleteRow?: (id: number) => void;
deleteRow is used in the "DataTable/MonitorsTable" component

2024-02-27 14:54 UTC, chamanbravo commented
Oh thank you for the clarification.
Thank you for your contribution. Please do star the repo and hope you will keep contributing.
If there's anything that needs change/improvement, feel free to open issues.
Thank you

2024-02-27 14:54 UTC, merged